//! CRAM fixture integration tests.
//!
//! These tests load the CRAM fixtures from `fixtures/` and run them through
//! the full analysis pipeline. They require:
//!   1. CRAM fixtures generated by `build_test_fixtures`
//!   2. GRCh38 reference FASTA in `ref/` (run `scripts/download-reference.sh`)
//!
//! Tests are skipped (not failed) if the reference is not present, so CI
//! without the reference still passes. Run `scripts/download-reference.sh`
//! to enable these tests locally.

mod fixture_helpers;

use std::fs::File;
use std::io::Read as _;
use std::path::PathBuf;

use nds_core::interpret::{Confidence, Subtype};
use nds_core::reader::Region;
use nds_core::reference::ReferenceSource;
use nds_core::{analyze, AlignmentSource, CursorCramSource};

use fixture_helpers::fixture_config;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..")
}

fn fixture_path(name: &str) -> PathBuf {
    repo_root().join("fixtures").join(name)
}

fn reference_path() -> PathBuf {
    repo_root().join("ref/GRCh38_no_alt_plus_hs38d1.fna")
}

fn reference_available() -> bool {
    reference_path().exists()
}

fn load_bytes(path: &PathBuf) -> Vec<u8> {
    let mut bytes = Vec::new();
    File::open(path)
        .unwrap_or_else(|e| panic!("open {}: {e}", path.display()))
        .read_to_end(&mut bytes)
        .unwrap();
    bytes
}

/// Reference source that reads chr17 and chr2 from the actual FASTA.
struct FastaReferenceSource {
    chr17_md5: [u8; 16],
}

impl ReferenceSource for FastaReferenceSource {
    fn fetch_sequence(&mut self, _region: &Region) -> nds_core::Result<Vec<u8>> {
        Ok(Vec::new())
    }
    fn chr17_md5(&mut self) -> nds_core::Result<[u8; 16]> {
        Ok(self.chr17_md5)
    }
}

fn analyze_cram_fixture(cram_name: &str) -> Option<nds_core::AnalysisResult> {
    if !reference_available() {
        return None;
    }

    let cram_path = fixture_path(cram_name);
    let crai_path = fixture_path(&format!("{cram_name}.crai"));

    if !cram_path.exists() {
        panic!(
            "Fixture not found: {} — run `cargo run --release --bin build_test_fixtures`",
            cram_path.display()
        );
    }

    let cram_bytes = load_bytes(&cram_path);
    let crai_bytes = load_bytes(&crai_path);

    // Build reference repository from FASTA for chr17 + chr2
    let ref_path = reference_path();
    let mut fasta_reader = noodles_fasta::io::indexed_reader::Builder::default()
        .build_from_path(&ref_path)
        .unwrap_or_else(|e| panic!("open reference: {e} (needs .fai)"));

    // Load full chromosomes — noodles CRAM needs position-indexed reference
    // where array index matches 0-based genomic position.
    let chr17_region = noodles_core::Region::new(
        "chr17",
        noodles_core::Position::try_from(1usize).unwrap()
            ..=noodles_core::Position::try_from(83257441usize).unwrap(),
    );
    let chr17_record = fasta_reader.query(&chr17_region).unwrap();
    let chr17_seq: Vec<u8> = chr17_record.sequence().as_ref().to_vec();

    let chr2_region = noodles_core::Region::new(
        "chr2",
        noodles_core::Position::try_from(1usize).unwrap()
            ..=noodles_core::Position::try_from(242193529usize).unwrap(),
    );
    let chr2_record = fasta_reader.query(&chr2_region).unwrap();
    let chr2_seq: Vec<u8> = chr2_record.sequence().as_ref().to_vec();

    let ref_seqs = vec![
        ("chr17".to_string(), chr17_seq),
        ("chr2".to_string(), chr2_seq),
    ];

    use nds_core::sources::offset_cursor::OffsetCursor;
    let cursor = OffsetCursor::new(vec![(0, cram_bytes)]);
    let mut source = CursorCramSource::from_cursor_with_ref(cursor, crai_bytes, ref_seqs)
        .unwrap_or_else(|e| panic!("open CRAM: {e}"));

    let header = source.read_header().unwrap();
    let chr17_md5 = header.chr17_md5().unwrap_or([0u8; 16]);
    let mut reference = FastaReferenceSource { chr17_md5 };
    let config = fixture_config();

    Some(analyze(&mut source, &mut reference, &config).unwrap())
}

// =========================================================================
// SV detection on CRAM fixtures
// =========================================================================

#[test]
fn cram_cn3_cmt1a_detected() {
    let Some(result) = analyze_cram_fixture("cn3_cmt1a_sv_only.cram") else {
        eprintln!("SKIP: reference not available (run scripts/download-reference.sh)");
        return;
    };
    assert_eq!(result.depth.estimated_cn, 3, "expected CN=3");
    assert_eq!(result.interpretation.confidence, Confidence::Full);
    assert_eq!(result.interpretation.subtype_call, Some(Subtype::CMT1A));
}

#[test]
fn cram_cn1_hnpp_detected() {
    let Some(result) = analyze_cram_fixture("cn1_hnpp_sv_only.cram") else {
        eprintln!("SKIP: reference not available");
        return;
    };
    assert_eq!(result.depth.estimated_cn, 1, "expected CN=1");
    assert_eq!(result.interpretation.confidence, Confidence::Full);
    assert_eq!(result.interpretation.subtype_call, Some(Subtype::HNPP));
}

#[test]
fn cram_cn2_negative_is_clean() {
    let Some(result) = analyze_cram_fixture("cn2_negative_control.cram") else {
        eprintln!("SKIP: reference not available");
        return;
    };
    assert_eq!(result.depth.estimated_cn, 2, "expected CN=2");
    assert_eq!(result.interpretation.confidence, Confidence::Full);
    assert_eq!(result.interpretation.subtype_call, None, "no SV expected");
}

#[test]
fn cram_cn2_with_snv_het_sv_is_clean() {
    // The cn2_with_snv_het fixture has SNV spikes but no SV — SV result should be CN=2
    let Some(result) = analyze_cram_fixture("cn2_with_snv_het.cram") else {
        eprintln!("SKIP: reference not available");
        return;
    };
    assert_eq!(
        result.depth.estimated_cn, 2,
        "expected CN=2 (no duplication)"
    );
    assert_eq!(result.interpretation.subtype_call, None);
}

#[test]
fn cram_segdup_artifact_not_called_as_dup() {
    let Some(result) = analyze_cram_fixture("cn2_segdup_artifact.cram") else {
        eprintln!("SKIP: reference not available");
        return;
    };
    assert_eq!(
        result.depth.estimated_cn, 2,
        "segdup artifact must NOT inflate CN"
    );
    assert_eq!(result.interpretation.subtype_call, None);
}

#[test]
fn cram_subthreshold_run_not_called() {
    let Some(result) = analyze_cram_fixture("cn2_subthreshold_run.cram") else {
        eprintln!("SKIP: reference not available");
        return;
    };
    assert_eq!(result.depth.estimated_cn, 2);
    assert_eq!(
        result.interpretation.subtype_call, None,
        "12kb run below min_reportable_run_length"
    );
}

#[test]
fn cram_complex_dup_gap_not_standard_cmt1a() {
    let Some(result) = analyze_cram_fixture("cn2_complex_dup_gap.cram") else {
        eprintln!("SKIP: reference not available");
        return;
    };
    // Complex dup with internal gap should NOT be classified as standard CMT1A
    assert_ne!(
        result.interpretation.subtype_call,
        Some(Subtype::CMT1A),
        "complex dup with gap should not be standard CMT1A"
    );
}
